### ISSUE TITLE
Server crash when opening the Redstonic Manual.

### ISSUE THREAD

**Issue by laserlemons** [Raizunne/Redstonic#1]
http://pastebin.com/rSBkZK55

Right clicking the manual will crash the server, not the client. Works in SSP.

**Comment by Raizunne** [comment]
Thank you, this has been fixed in version 1.01. Please update!
http://raizunne.github.io/Mods/Redstonic/downloads.html

**Comment by Raizunne** [comment]
Fixed in version 1.01.
