### ISSUE TITLE
ctd with batteries with only enderio installed

### ISSUE THREAD

**Issue by pklizard** [Raizunne/Redstonic#11]
forge ver 1291
enderio ver 2.2.8.367
redstonic ver 1.3
no thermal expansion

game immediately crashes to desktop when attempting to put any battery into the drill modifier gui (charged or uncharged).  cannot log back into world without rolling back or mceditting.
crashlog: http://www.filedropper.com/crash-2015-04-11014031-client

**Comment by Raizunne** [comment]
Yes, this is a problem I encountered. Uploading a fix in a few mins. Thank you for reporting!

**Comment by Raizunne** [comment]
Fixed as of version 1.3.1, please download it here:
http://raizunne.github.io/Mods/Redstonic/downloads.html

Sorry again for the corruption! This will hopefully fix it! Any other problems make sure to let me know!

**Comment by pklizard** [comment]
that got it!! thanks so much for the quick fix, fantastic mod!

**Comment by pklizard** [comment]
also, there were a couple of missing recipes but i ended up minetweaking in my own
here's a cut/paste if you want to use these or if you just want to see which ones are missing

//adding missing redstonic recipes
recipes.addShaped(<Redstonic:EnergizerCapsule>, [[darksteel, darksteel, darksteel], [darksteel, <EnderIO:blockIngotStorage:4>, darksteel], [darksteel, darksteel, darksteel]]);

recipes.addShaped(<Redstonic:basicBattery:80>.withTag({maxEnergy: 500000, Energy: 0}), [[null, redstone, null], [<ore:dustCoal>, <ore:blockIron>, <ore:dustCoal>], [redstone, basiccap, redstone]]);

recipes.addShaped(<Redstonic:energizedBattery:80>.withTag({maxEnergy: 5000000, Energy: 0}), [[null, redalloy, null], [silver, <EnderIO:blockIngotStorage:1>, silver], [redalloy, <Redstonic:basicBattery:80>, redalloy]]);

**Comment by Raizunne** [comment]
Yeah, the recepies are there for TE but completely forgot to add the EIO equivalent. Thanks for reminding me! Sadly I'm unable to quick fix this so it'll have to wait
