### ISSUE TITLE
Server log spam

### ISSUE THREAD

**Issue by bochen415** [Raizunne/Redstonic#12]
I'm not sure if it's a Redstonic bug but I get constant server log spam when I'm picking up items.

example: 
http://paste.ubuntu.com/10911710/

When some kind of an item magnet is used and the inventory is full (and the items just kinda float around)  the spam is generating without any items being picked up and it sure is fast.

Redstonic-v1.3.2
Forge 1388

**Comment by bochen415** [comment]
Yup, it's Redstonic. I removed it temporarily from the server (and the client) and the log spam stopped.

**Comment by Raizunne** [comment]
Thank you! This was indeed my problem. I've fixed it in the new release 1.3.3 - 
You can get it here: http://raizunne.github.io/Mods/Redstonic/downloads.html
