### ISSUE TITLE
Crash whenever shift right-clicking without hotswap module.

### ISSUE THREAD

**Issue by SacredTomba** [Raizunne/Redstonic#13]
http://pastebin.com/raw.php?i=8vFtwcHZ is the crashlog. Don't ask me why I would be possessed to do such a thing, but hey, it happened.

**Comment by Raizunne** [comment]
Could you tell me which augments you have? From what I see from the crashlog I think you had Magnet, Energy and Speed?

**Comment by SacredTomba** [comment]
That is correct.

**Comment by Raizunne** [comment]
It should be fixed as of version 1.4, if the problem persists please make sure to tell me!
