### ISSUE TITLE
Dual speed augments confuses the Redstonic Modifier

### ISSUE THREAD

**Issue by 4rz0** [Raizunne/Redstonic#15]
When I try to put in 2 Class2 speed augments into my drill (Fortuitous drill head, Electrum drill body, Resonant Flux Capacitor), the assembler stops working with the drill parts.
To make it work again, I have to put out all drill parts and put in something else, for example my sword.

If this happens because dual speed upgrades aren't allowed, I suggest adding some kind of hint or failure message to the interface or tooltips.

**Comment by Raizunne** [comment]
Sorry for taking too long to reply, yes, you cannot use the same augment more than once in a drill. I'm working on revamping the Redstonic Modifier to make it more intuitive. I'll work on fixing everything on the next update. Thanks for the report!

**Comment by 4rz0** [comment]
Neat, thanks for acknowledging/fixing it \o/
