### ISSUE TITLE
Energizer Capsule cannot be filled

### ISSUE THREAD

**Issue by smbarbour** [Raizunne/Redstonic#18]
The Energizer Capsule requires 32,000 mB of redstone, but the Fluid Transposer can only hold 10,000 mB of fluids.  The Fluid Transposer will not begin filling an item until it contains enough to fill the item, and thus it cannot be filled.

**Comment by Raizunne** [comment]
Yes, this was changed in a recent TE update, I'll change the recipe to use the Induction Smelter. Thanks for reporting! I'm releasing a update that fixes a few bugs in an hour or so.
