### ISSUE TITLE
[Crash]: Array Index Out Of Bounds Crash!

### ISSUE THREAD

**Issue by Lanse505** [Raizunne/Redstonic#2]
Hello!

One of our testers crashed due to a Array Index Out of Bounds after looking into the drill.

CrashLog:
http://pastebin.com/SW59NAnJ

It Seems to be related to him upgrading his drill with a TE upgrade

He says: "I switched it from disassemble to assemble mods while the drill parts are in the machine and boom crash"

**Comment by JoeSchmo2840** [comment]
Also the crash to desktop is persistant. Everytime a player in that chunk logs in CTD

**Comment by Labs4077** [comment]
Here's the openeye report if it helps at all:

http://openeye.openmods.info/crashes/e273887171e69da4de1385e529fbb872

**Comment by Raizunne** [comment]
So he placed the parts of the drills while it was in dissassemble mode, then clicked on assemble and it crashed?

Also does he remember which items were in the machine? or atleast which augment was in the machine?

**Comment by Raizunne** [comment]
Alright I managed to replicate the crash. It seems that he was trying to use a Hotswap Augment?

**Comment by Towsty** [comment]
So the drill was in the machine (assembled in assemble mode) - in the augment slot was a speed and a hot swap upgrade

I switched to disassemble
Then it crashed

It was all the electrum based parts on the drill
The body with 2 upgrades
Reinforced Flux Cap
Heavy Drill head

**Comment by Raizunne** [comment]
I *THINK* I've managed to fix the issue you are talking about. Could you test it from this test version? This should also clear the crashed you were having when you loaded the chunk.
http://raizunne.github.io/Mods/Redstonic/Test.html

**Comment by JoeSchmo2840** [comment]
Testing now

**Comment by JoeSchmo2840** [comment]
Fixed

**Comment by Towsty** [comment]
Fantastic, thank you!

**Comment by Raizunne** [comment]
Thank you for your help! I'll post an official release in a sec. 
If you need anything else hit me up!

**Comment by JoeSchmo2840** [comment]
No problem thank you for the awesome mod and we will keep putting it to its paces.

**Comment by Lanse505** [comment]
Btw Raizunne, I would like to talk to you about possibly including your mod in Resonant Rise 3 and opening a dialog between us and you :)

**Comment by Raizunne** [comment]
Im up for it! You can hit me up on twitter @Raizunne or if you prefer you can email me raizunne@hotmail.com!
