### ISSUE TITLE
[suggestion] Add drill speed setting

### ISSUE THREAD

**Issue by 4rz0** [Raizunne/Redstonic#24]
Add a way to slow down drill power.
The End drill, while useful freeing large areas of stuff, us too powerful for controlled mining/digging.

I suggest adding a mode system where you can switch (with a key and/or trough GUI) between full and reduced mode.
Best would be if it's configurable ingame how fast it should be, so that I can set up my drill depending on what I want to do.

**Comment by Raizunne** [comment]
Yeah I thought about adding a way to destroy blocks one by one for precise mining but didn't add it for some reason, i'll add it in the next update. Thank!

**Comment by Raizunne** [comment]
Added Low Power Mode in version 1.4.7. Sneak right click to activate.
