### ISSUE TITLE
right click torch placement destroys blocks

### ISSUE THREAD

**Issue by Delerium** [Raizunne/Redstonic#25]
Alot of mods add blocks that don't take up the whole space, allowing you to target the block behind it.  Unfortunately when using the redstonic drill, the right-click torch placement does not check the space the torch would go for an existing block, and places it anyway, deleting (not just breaking the block, the item is gone permanently) whatever was there previously...like a chest full of items. Thankfully only the chest itself gets deleted and items spill out.  This happens alot on mistake when trying to open chests with right click and not quite targeting the chest.

**Comment by Raizunne** [comment]
I could have sworn I had fixed that, but I just checked and that is a big problem! Sorry about that, hopefully you didnt lose anything important! I'll have a fix in a bit. Thank you for reporting!

**Comment by Delerium** [comment]
just some simple chests. nothing major.

**Comment by Raizunne** [comment]
Fixed in version 1.4.7
