### ISSUE TITLE
Drill head toggle hotkey would be nice

### ISSUE THREAD

**Issue by Delerium** [Raizunne/Redstonic#26]
I looked through the keyboard hotkeys and couldn't find one, but it would be nice to have a keyboard hotkey for swapping drill heads.  Right now when you sneak-right click to change drill heads, you have to make sure you aren't targeting a block or else it doesn't work. this requires me to turn around and look at empty space when mining, which gets tedious if, like me, you use one head for fortune (diamond/lapis/coal/etc), and one head for speed.

**Comment by Raizunne** [comment]
Yeah there's no keybinds for that stuff. I can add some for sure in the next update! Thanks for the suggestion.
