### ISSUE TITLE
Crash when crafting a new drill~

### ISSUE THREAD

**Issue by AngieTheDemoness** [Raizunne/Redstonic#27]
Hello, I was messing up a bit with your mod to test out before final publication of a modpack and stood upon this crash

https://gist.github.com/AngieTheDemoness/1bdf35497ae9186fb1b2

It happens when I try to craft a drill inside the redstonic modifier.

**Comment by Raizunne** [comment]
Yes I've found this bug, im fixing it and releasing a new version today!

**Comment by AngieTheDemoness** [comment]
Thanks !

**Comment by Raizunne** [comment]
Fixed in version 1.4.8. Thanks!
