### ISSUE TITLE
Some Recipes not using Ore Dict

### ISSUE THREAD

**Issue by CandiceJoy** [Raizunne/Redstonic#28]
Throughout the mod, some recipes don't use the oredict and some do.  For example, the electrum ingots in the electrum body DO use the oredict, but the electrum ingots in the electrum blade do not.  This makes having two mods that add electrum very difficult to work with if we install your mod as well.  Could you modify your recipes to the oredict equivalents throughout the mod?  (Enderium, Electrum gears, Electrum Ingots, etc etc etc)

**Comment by Raizunne** [comment]
You're absolutely right. I forgot to add this since the recipes for the drill and the sword were made separate from each other. I dont have access to a computer right now so I'll add it as soon as I can. Thank you for reminding me!

**Comment by Raizunne** [comment]
Fixed in version 1.4.9
