### ISSUE TITLE
Issue with Extra Utilities and Redstonic (NEI Subsets stop working)

### ISSUE THREAD

**Issue by smbarbour** [Raizunne/Redstonic#29]
In reference to https://github.com/rwtema/extrautilities/issues/678, NullPointerExceptions are occurring in Redstonic's item code where getMaxEnergyStored is overridden.

This issue is fixed with these changes: https://github.com/smbarbour/Redstonic/commit/1d1bd4aab10914e0fc9a505c69c08ee0f2ffb583

I would have submitted a PR, but my IDE changed the code indentation from spaces to tabs, making a mess of the line changes.

**Comment by Raizunne** [comment]
Thank yu! Ill try to add it as soon as I can, I have no pc right now so It'll have to be next week :(

**Comment by hron84** [comment]
@Raizunne is there any chance to get this bug fixed? I experiencing this issue with Horizons Daybreaker, and NEI stops working because this.

**Comment by Raizunne** [comment]
Fixed in version 1.4.9.
