### ISSUE TITLE
Configs

### ISSUE THREAD

**Issue by Nentify** [Raizunne/Redstonic#30]
Hey

I found your mod the other day and I really like the look of it, just what I needed for my modpack. However, I have a few questions.

Would it be possible to have some more config options? For example:

- Changing the energy values of the different batteries and capacitors
- Changing the energy used per block mined
- Maybe make it easier to enable/disable some components - eg. I don't have enderio and it'd be nicer to declutter NEI. I would also disable the 3x3 module for this pack, but this can be done with MineTweaker so this one isn't a big deal

I may have missed some things that perhaps other people would find useful, but config options, at least for the energy, would be really nice.

Also - What is the redstonic container/what does the redstonic container max capacity config option do?

Thanks a lot, love the mod!

Edit: Unless you're against configs, maybe give each module a config? Like have a drill heads section, then have all the drill heads and their different properties defined (mining speed, RF use) and then have a battery section with all their batteries and their properties (capacity, any others). This would be ideal but something simpler would be fine too. Thought I'd just share my ideas. :P

Edit 2: Also, one thing. How does the block placer work? :3

**Comment by Raizunne** [comment]
I had the structure for making configs but couldnt think of something to put in them. Im adding configs to all of the things you mentioned, as for number 3, do you mean being able to remove an item from the mod? I'll add that too though :P.

As for the redstonic container, Its something I made that I never released. Its somewhat like the OpenBlocks /dev/null, but holds 256 items. I didnt release it could it was too close to that.

The block place works by right clicking the drill on the block you want to place. It will give you a sound. Then just right click to place the block. Keep in mind that this removes the ability to place torches with a right click.

Thanks for the suggestions!

**Comment by Nentify** [comment]
> do you mean being able to remove an item from the mod?

Yes

If you need any more help/advice or anything just let me know, happy to help. ^^

**Comment by Raizunne** [comment]
If you have any other suggestions for items or features theyre appreciated!
