### ISSUE TITLE
Various Minor Issues

### ISSUE THREAD

**Issue by Nentify** [Raizunne/Redstonic#31]
1. Opening the manual and going Machines > Driller then pressing return twice doesn't allow you to go to the book index page. Same applies to going 2 deep into the swords pages

2. The sword augments page have the wrong augments (the pictures/items) as well

3. http://i.nentify.me/V1TyivAX.png Should this say Redstonic Modifier?

**Comment by Raizunne** [comment]
Sorry for the long delay, I had no pc for weeks! I'm starting to work on the mod again.
1. I've fixed this and is coming in the next release.
2. Yes, I somehow forgot to add the augments for the sword. Thanks!
3. Yup, recently changed the name of the machine to Redstonic Modifier and forgot to change the tooltip!

Thanks for reporting!
