### ISSUE TITLE
Redstonic Driller and Galacticraft Silicon Ore

### ISSUE THREAD

**Issue by HowardRoark2016** [Raizunne/Redstonic#32]
I am using Windows 7 Ultimate x64-bit SP1 and Java 8 update 11 (build 1.8.0_11-b12) and using the FtB Launcher v1.4.8 to play MC 1.7.10 SSP via FtB Horizons: Daybreaker v1.1.0 in a Realistic World Gen Alpha-generated world with 4.5GB of RAM allocated to FtB. The version of Galacticraft in this pack is GalacticraftCore-1.7-3.0.12.350. The version of Redstonic in this pack is Redstonic-v1.4.8. The version of CoFH Core in this pack is CoFHCore-[1.7.10]3.0.3-303. 

I have mined up some Galacticraft Silicon Ore using the silky setting on a Mekanism's Digital Miner. If I break those ore blocks using a Redstonic Drill in hand (or any pick greater than wooden), the Silicon Ore block drops Galacticraft's Raw Silicon item, which is the expected result. However, If I place that ore block in front of a Redstonic Driller, I do not get Galacticraft's Raw Silicon. Instead, I get a block called "tile.gcBlockCore.null.name" which has no recipe in NEI. That block the Driller drops appears to share the same item ID but different metadata as the Silicon Ore itself. The Silicon Ore block is 873:8. The block the Driller drops is 873:0. By the way, Raw Silicon is 4454:2. 

I tried the Driller with every drill head only to get the same results with the Silicon Ore.

**Comment by Raizunne** [comment]
Im going to be testing this, I've had issues with blocks not dropping with the correct metadata. I'll have it going in the next release. Thanks for reporting!
