### ISSUE TITLE
Nullpointer while registering recipes in 1.4.9

### ISSUE THREAD

**Issue by e3r** [Raizunne/Redstonic#34]
Hi,

I'm getting a NullPointerException on load with the 1.4.9 version - 1.4.8 works fine, though.
Looks like it's happening while registering the TE-recipes. 

Details (stacktrace and modlist):
http://pastebin.com/s7cpKNk3

**Comment by CandiceJoy** [comment]
Confirmed.  http://pastebin.com/sSjxMTsf

**Comment by CandiceJoy** [comment]
It's something to do with the addRecipe call here https://github.com/Raizunne/Redstonic/blob/master/src/main/java/com/raizunne/redstonic/RedstonicRecipes.java#L160-L163

and how it's different from the other addRecipe calls.

**Comment by CandiceJoy** [comment]
I'll submit a PR to fix it.

**Comment by CandiceJoy** [comment]
PR created.  https://github.com/Raizunne/Redstonic/pull/36

**Comment by CandiceJoy** [comment]
Can confirm that this is fixed.  Yay!
