### ISSUE TITLE
The Driller cant mine more than 1x3x3

### ISSUE THREAD

**Issue by BlazingGamer** [Raizunne/Redstonic#38]
Hello, the Driller is working incorrectly.
When I place driller + Heavy DH it only mines 1x3x3 (or 3x3x1) block and then stops. Seems it mines block connected to it. Then, could you make for example "Driller Pipe" that appears after driller and mines the same area as driller but 1 block farther and drops nothing (like the BC's Mining Well Pipe)?

**Comment by Raizunne** [comment]
Do you have a chest behind the driller? The driller puts all of its items in a chest behind it, it will not drill until it deposits the items on the chest. I'm not sure if it specified this in the documentation.

Tell me if you have any other problems!
