### ISSUE TITLE
Crash When Loading up the world

### ISSUE THREAD

**Issue by SJ1133** [Raizunne/Redstonic#4]
This is Crash i get ever 1/3 Times i load the game. http://pastebin.com/E4EAmGP4

**Comment by bochen415** [comment]
I had intermittent isp problems and same thing occurs.
http://paste.ubuntu.com/10692795/

**Comment by Raizunne** [comment]
It looks like the problem is when players dont have internet access. I'll fix this in the next version. Thanks for the input!

**Comment by Raizunne** [comment]
Issue fixed as of version 1.2.1, please follow up if problem persists.
