### ISSUE TITLE
Crash when trying to craft drill + Few other minor issues

### ISSUE THREAD

**Issue by lilmoefow** [Raizunne/Redstonic#42]
When trying to craft a drill in the Redstonic Table,  It crashes as soon as i put the final piece into the gui.

CrashLog: http://pastebin.com/fF5PrB0K
FML-Client-Log: https://gist.github.com/lilmoefow/54797eb714658ae1ece9dd463c7e3613

There also seems to be a localization issue with the naming of the GUI
http://imgur.com/a/P6UNI

Aswell as the GlowSteel Ingot is missing a texture.

**Comment by Raizunne** [comment]
Fixed in 1.5.2, uploading in about 30 min. Thanks for the report!

**Comment by Raizunne** [comment]
Fixed in 1.5.2
https://minecraft.curseforge.com/projects/redstonic/files/2339886
