### ISSUE TITLE
Hotswap wont let me put in a drill head for swap

### ISSUE THREAD

**Issue by Wraither** [Raizunne/Redstonic#43]
Basically first time i used it was perfect 100% but that drill was taken by a sticky mob (infernal mobs mod) and was blown up by lightning, now it does not work at all. I can put it in the drill and it registers, but when i try to put a drill head into the augment it does nothing. I looked into the manual, heck i even tried emptying it and it still wont work. Mod works great any other way, if you want i can send a list of all my mods i have (71 mods) just have to ask. ^.^
**THE ISSUES-**
1-the hotswap augment wont craft with a drill head even though it is empty

**Comment by Raizunne** [comment]
You're trying to set a drill head to the augment but it wont let you? Does it say it has a drill head in the augment? (in the tooltip it should show you which head the augment has)

**Comment by Wraither** [comment]
i checked it, and it says 
Head:empty head
and if i try to craft it with another drill head it does not work at all

**Comment by Raizunne** [comment]
If you use advanced tooltips(F3+H) how many NBT tags does it have (if any)? It should say "NBT: 1tag(s)" or nothing at all

**Comment by Wraither** [comment]
it says

Redstonic:HotSwapAugment
it has one general id (5049)

**Comment by Raizunne** [comment]
This version is no longer supported, update to v2
