### ISSUE TITLE
1.7.10 batterys have a problem with logistics pipes

### ISSUE THREAD

**Issue by coehlrich** [Raizunne/Redstonic#45]
when i put the recipes in the logistics pipes crafting table and request some it doesn't come  it only crafts one and doesn't put it anywhere (i think this is a problem with the damage values for the crafting recipes because logistics pipes is expecting one with a damage value of 0 and it gets one with a damage value of 80) also i am using the project ozone 2 reloaded modpack.

**Comment by Raizunne** [comment]
This version is no longer supported, update to v2
