### ISSUE TITLE
Failed update checks cause massive lag spikes

### ISSUE THREAD

**Issue by bernds** [Raizunne/Redstonic#50]
I'm playing Project Ozone 2, which has Redstonic 1.4.11. When I'm in the Nether, there are massive lag spikes where the game freezes for a few seconds; these seem to coincide with log messages about java.io.FileNotFoundException: https://raw.githubusercontent.com/Raizunne/Redstonic/master/src/versions/latest.txt

I seem to have fixed that by hexediting the com/raizunne/redstonic/Proxy/ClientProxy.class file and replacing "master" with "1.7.10"; that file exists. But it would be better if the network access wasn't there, or could be turned off in the config.

**Comment by bernds** [comment]
Ok, the lag is back, so this doesn't seem to be the cause after all :( Still a small bug though.

**Comment by Raizunne** [comment]
This version is no longer supported, update to v2
