### ISSUE TITLE
[1.12.2] Crash upon constructing drills with batteries cheated in from JEI

### ISSUE THREAD

**Issue by ComplainingSkelzie** [Raizunne/Redstonic#53]
Crash report here: https://pastebin.com/6xSRHUHN

EDIT: This actually seems to happen upon constructing any drill, more often than not. I have both crashed and not crashed during various attempts to assemble a drill with a heavy drill head, iron drill body, and large battery.

EDIT 2: The crash reliably happens when I put the battery into the redstonic modifier straight from JEI. If the battery is in my inventory before going into the redstonic modifier, the crash doesn't happen. This case was tested with a drill made with a silky drill head, iron drill body, and infinite battery.

**Comment by Raizunne** [comment]
Fixed in v2.1
