### ISSUE TITLE
[1.12.2] All redstonic swords using the iron handle have 1 attack damage

### ISSUE THREAD

**Issue by ComplainingSkelzie** [Raizunne/Redstonic#56]
Tested with the following compositions:
- Iron handle, diamond blade, infinite battery, berserk 2 augment: 1 attack damage
- Iron handle, diamond blade, infinite battery, no augment: 1 attack damage
- Iron handle, iron blade, infinite battery, no augment: 1 attack damage
- Iron handle, diamond blade, energized battery, no augment: 1 attack damage
- Iron handle, iron blade, energized battery, berserk 1 augment: 1 attack damage
- Wooden handle, iron blade, no battery, no augment: 7 attack damage
- Wooden handle, diamond blade, no battery, no augment: 9 attack damage

This is not merely a display bug. These damage numbers do apply to the actual damage done by the sword swing.

**Comment by Raizunne** [comment]
Tested with some recent changes and im getting the actual damage.
There was a bug with the infinite battery and thats fixed, but with the other batteries im getting no error. Was the sword charged?

**Comment by ComplainingSkelzie** [comment]
I can confirm that the issue was with the sword not being charged. Charging a sword with a non-infinite battery gives it the correct damage.
