### ISSUE TITLE
Login crash

### ISSUE THREAD

**Issue by JoeSchmo2840** [Raizunne/Redstonic#7]
[B#283]  Description: Unexpected error
[B#283]  
[B#283]  java.lang.NullPointerException: Unexpected error
[B#283]         at com.raizunne.redstonic.Client.BlockLooking.init(BlockLooking.java:28)
[B#283]         at com.raizunne.redstonic.Handler.RedstonicEventHandler.RenderGameOverlayEvent(RedstonicEventHandler.java:34)
[B#283]         at cpw.mods.fml.common.eventhandler.ASMEventHandler_638_RedstonicEventHandler_RenderGameOverlayEvent_RenderGameOverlayEvent.invoke(.dynamic)
[B#283]         at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[B#283]         at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[B#283]         at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:895)
[B#283]         at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:102)
[B#283]         at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1325)
[B#283]         at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
[B#283]         at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
[B#283]         at net.minecraft.client.main.Main.main(SourceFile:148)
[B#283]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#283]         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#283]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#283]         at java.lang.reflect.Method.invoke(Unknown Source)
[B#283]         at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#283]         at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by JoeSchmo2840** [comment]
Whoops this looks like a duplicate of Issue #6

**Comment by Raizunne** [comment]
I've fixed this (or atleast that's what I've gotten from testing this) in the new version 1.2.
You can get it here: http://raizunne.github.io/Mods/Redstonic/downloads.html

**Comment by Raizunne** [comment]
Issue fixed as of version 1.2.1, please follow up if problem persists.
