### ISSUE TITLE
Server Crashed after updating a few mods

### ISSUE THREAD

**Issue by aldra2012** [Raizunne/Redstonic#8]
http://pastebin.com/KuspG8xM

**Comment by Raizunne** [comment]
Thank you, this is caused by missing EnderIO (optional mod), which was not intended. I will fix this and post a fix in a few hours.

**Comment by Raizunne** [comment]
Fixed this on version 1.2.2, you can get it here:
http://raizunne.github.io/Mods/Redstonic/downloads.html
