### ISSUE TITLE
Drills drain RF from SimplyJetpacks' JetPlates and Flux Packs

### ISSUE THREAD

**Issue by Neon-Beta** [Raizunne/Redstonic#9]
It seems that any drills created, will continually drain RF from SimplyJetpacks' JetPlates and all tiers of Flux-Packs.

I wasn't sure if this was a problem on Redstonic's side or SimplyJetpacks side, but since this problem only occurs with redstonic drills, I thought I'd report it here first.
-edit-
This also seems to occur on a more drastic level with PowerConverters own Universal charger with the drill inside any sort of inventory (autonomous activator, chest etc) and draining what seemingly the max power input of a drill (end drill seems to pull 50K RF/t)

**Comment by Raizunne** [comment]
This might be my problem, sorry about that! I'll make a update in a few. Thanks for reporting!

**Comment by Raizunne** [comment]
Fixed in version 1.3, you can get it here: 
http://raizunne.github.io/Mods/Redstonic/downloads.html

**Comment by Neon-Beta** [comment]
Everything I mentioned seems to work properly now, thanks!

And thanks such an awesome mod :)
